<!-- Google Code für ein Remarketing-Tag -->
<!--------------------------------------------------
Remarketing-Tags dürfen nicht mit personenbezogenen Daten verknüpft oder auf Seiten platziert werden, die sensiblen Kategorien angehören. Weitere Informationen und Anleitungen zur Einrichtung des Tags erhalten Sie unter: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$currency = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
if($_product):
?>
<script type="text/javascript">
    var google_tag_params = {
        ecomm_prodid: '<?php echo $_product->getSku() ?>',
        ecomm_pagetype: 'product',
        ecomm_totalvalue: '<?php echo Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice(), true); ?>',
    };
</script>
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 1000772783;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1000772783/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
    <!-- End Google Code for Remarketing -->
<?php endif; ?>