<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_GermanSetup is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2012 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     0.1.0
 */
/**
 * Checkout Agreements
 *
 * @category  FireGento
 * @package   FireGento_GermanSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013 FireGento Team (http://www.firegento.de). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   $Id:$
 * @since     1.2.2
 */

/**
 * @var $this FireGento_GermanSetup_Block_Checkout_Agreements
 */

/** @var $helper FireGento_GermanSetup_Helper_Data */
$helper = Mage::helper('germansetup');
$agreements = $this->getAgreements();
?>

<?php if (!$agreements) return; ?>

<form action="" id="checkout-agreements" onsubmit="return false;">
    <div class="checkout-comments">
        <div for="orderComment"><?php echo $this->__('Wie bist Du auf uns aufmerksam geworden:'); ?></div>
        <select id="orderCommentSelect" name="oderCommentsSelect">
            <option value=""></option>
            <option value="Facebook">Facebook</option>
            <option value="Google Suche">Google Suche</option>
            <option value="Freunde">Freunde</option>
        </select>
        <div class="checkout-comments-text">
            <label for="Magazin"><?php echo $this->__('Magazin:'); ?></label>
            <input name="Magazin" id="Magazin">
        </div>
        <div class="checkout-comments-text">
            <label for="Handel"><?php echo $this->__(' Im Handel gesehen:'); ?></label>
            <input name="Handel" id="Handel">
        </div>
        <div class="checkout-comments-text">
            <label for="Andere"><?php echo $this->__('Andere:'); ?></label>
            <input name="Andere" id="Andere">
        </div>
    </div>
<ol class="checkout-agreements">
<?php foreach ($agreements as $agreement): ?>
    <li>
        <p class="agree">
            <?php if($agreement->getIsRequired()): ?>
                <input type="checkbox" id="agreement-<?php echo $agreement->getId()?>" name="agreement[<?php echo $agreement->getId()?>]" value="1" title="<?php echo $this->htmlEscape($agreement->getCheckboxText()) ?>" class="checkbox" />
            <?php endif; ?>
            <label <?php if($agreement->getIsRequired()): ?>for="agreement-<?php echo $agreement->getId()?>"<?php endif; ?>><?php echo $agreement->getIsHtml() ? $agreement->getCheckboxText() : $this->escapeHtml($agreement->getCheckboxText()) ?></label>
            <a href="<?php echo $helper->getAgreementUrl($agreement) ?>" onclick="window.open(this.href, '', 'width=600,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes').focus(); return false;"><?php echo $this->__('[Show]') ?></a>
        </p>
    </li>
<?php endforeach ?>
</ol>
</form>
