<h1>Händlerliste</h1>

<div style="margin-bottom:20px;" id="haendlersuche" class="mod_article block">

    <strong>Deutschland</strong>
    <!-- indexer::stop -->
    <section class="mod_cataloglist block">

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first odd">
                <tr class="item  first odd">
                    <td class="field name">tapir</td>
                    <td class="field adress">Georgiring 4<br>+49 (0)800 8274767<br></td>
                    <td class="field city">04103 Leipzig</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Love It Green</td>
                    <td class="field adress">Eppendorfer Landstraße 98<br>+49 (0)40 65 86 69 55<br></td>
                    <td class="field city">20249 Hamburg</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first odd">
                <tr class="item  first odd">
                    <td class="field name">ReiseShop</td>
                    <td class="field adress">Walkerdamm 1<br>+49 (0)431 95661<br></td>
                    <td class="field city">24103 Kiel</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Unterwegs Kiel</td>
                    <td class="field adress">Andreas-Gayk-Straße 23<br>+49 (0)431 99040955<br></td>
                    <td class="field city">24103 Kiel</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first odd">
                <tr class="item  first odd">
                    <td class="field name">Intersport Knudsen</td>
                    <td class="field adress">Holstenstrasse 79<br>+49 (0)431 979919-111<br></td>
                    <td class="field city">24103 Kiel</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Intersport Knudsen</td>
                    <td class="field adress">Mühlendamm 1<br>+49 (0)431 979919-311<br></td>
                    <td class="field city">24113 Kiel</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Angeln & Mehr</td>
                    <td class="field adress">Langebrückstraße 20<br>+49 (0)431 76 72 76<br></td>
                    <td class="field city">24340 Eckernförde</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Unterwegs Oldenburg</td>
                    <td class="field adress">Gaststraße 27<br>+49 (0)441 9987666<br></td>
                    <td class="field city">26122 Oldenburg</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">PL-Outdoor</td>
                    <td class="field adress">Ludwigstraße 8<br>+49 (0)471 29009312<br></td>
                    <td class="field city">27570 Bremerhaven</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">Unterwegs Bremen</td>
                    <td class="field adress">Domshof 14-15<br>+49 (0)421 3365523<br></td>
                    <td class="field city">28195 Bremen</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first odd">
                <tr class="item  first odd">
                    <td class="field name">alles für globetrotter</td>
                    <td class="field adress">Ostertorsteinweg 85<br>+49 (0)421 74734<br></td>
                    <td class="field city">28203 Bremen</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">Unterwegs Celle</td>
                    <td class="field adress">Rabengasse 8<br>+49 (0)5141 909799<br></td>
                    <td class="field city">29221 Celle</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Unterwegs Münster</td>
                    <td class="field adress">Rosenstraße 10<br>+49 (0)251 48820834<br></td>
                    <td class="field city">48143 Münster</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">Ski und Sport Profis</td>
                    <td class="field adress">Töngesstraße 55<br>+49 (0)6136 95 33 88 1<br></td>
                    <td class="field city">55129 Mainz</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Breuninger</td>
                    <td class="field adress">Am Main-Taunus-Zentrum<br>+49 (0)69 69 52 20 0<br></td>
                    <td class="field city">65843 Sulzbach (Taunus)</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">Breuninger</td>
                    <td class="field adress">Marktstraße 1-3<br>+49 (0)711 21 10<br></td>
                    <td class="field city">70173 Stuttgart</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">Basislager</td>
                    <td class="field adress">Kaiserstraße 231<br>+49 (0)721 9209060<br></td>
                    <td class="field city">76133 Karlsruhe</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Sport Praxentaler</td>
                    <td class="field adress">Maximilianstraße 2<br>+49 (0)861 98 78 24 9<br></td>
                    <td class="field city">83278 Traunstein</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Intersport Prosport</td>
                    <td class="field adress">Grenzstraße 83<br>+49 (0)821 44 45 89 0<br></td>
                    <td class="field city">86165 Augsburg</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">Rider's Heaven</td>
                    <td class="field adress">Immenstädter Str. 9<br>+49 (0)8321 6909200<br></td>
                    <td class="field city">87527 Sonthofen</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Freilauf</td>
                    <td class="field adress">Untere Karlstraße 9-11<br>+49 (0)9131 916150<br></td>
                    <td class="field city">91054 Erlangen</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">lemon tree</td>
                    <td class="field adress">Sophienstr. 27<br>+49 (0)921 53047555<br></td>
                    <td class="field city">95444 Bayreuth</td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Unterwegs Erfurt</td>
                    <td class="field adress">Schlösserstraße 28<br>+49 (0)361 6017780<br></td>
                    <td class="field city">99084 Erfurt</td>

                </tr>
                </tbody>
            </table>
        </div>
    </section>
    <!-- indexer::continue -->

    <strong>Österreich</strong><!-- indexer::stop -->
    <section class="mod_cataloglist block">

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first last even">
                <tr class="item  first last even">
                    <td class="field name">Eco Lodge</td>
                    <td class="field adress">Fohrafeld 11<br>+43 2748 74 06 0<br></td>
                    <td class="field city">3233 Kilb</td>

                </tr>
                </tbody>
            </table>
        </div>


        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Sport Wöll</td>
                    <td class="field adress">Pertisau 11c<br>+43 5243 58 71<br></td>
                    <td class="field city">6213 Eben am Achensee</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first last even">
                <tr class="item  first last even">
                    <td class="field name">Sporthaus Unterlercher</td>
                    <td class="field adress">Zillertalstraße 10<br>+43 (0)5288 6767-0<br></td>
                    <td class="field city">6263 Fügen</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first last even">
                <tr class="item  first last even">
                    <td class="field name">Sport Kessler</td>
                    <td class="field adress">Walserstraße 73<br>+43 5517 36 85 40<br></td>
                    <td class="field city">6991 Riezlern</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first last even">
                <tr class="item  first last even">
                    <td class="field name">Sport Passler</td>
                    <td class="field adress">Ausserrotte 60<br>+43 487 3520333<br></td>
                    <td class="field city">9963 Sankt Jakob im Deffereggen</td>

                </tr>
                </tbody>
            </table>
        </div>

    </section>
    <!-- indexer::continue -->

    <strong>Schweiz</strong>
    <!-- indexer::stop -->
    <section class="mod_cataloglist block">

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Sports Discount</td>
                    <td class="field adress">Rue de Genève 17<br>+41 21 311 00 74<br></td>
                    <td class="field city">1003 Lausanne</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Side Cut Sports</td>
                    <td class="field adress">Gypsera 223<br>+41 26 412 10 58<br></td>
                    <td class="field city">1716 Schwarzsee</td>
                </tr>
                </tbody>
            </table>

        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Werrens Art</td>
                    <td class="field adress">Rawilstrasse 10<br>+41 33 733 33 19<br></td>
                    <td class="field city">3775 Lenk im Simmental</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Krüger Sport</td>
                    <td class="field adress">Bahnhofstrasse 6<br>+41 27 927 14 63<br></td>
                    <td class="field city">3987 Riederalp</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Number One</td>
                    <td class="field adress">Pfistergasse 25<br>+41 41 241 01 21<br></td>
                    <td class="field city">6003 Luzern</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">STS Sport Trend Shop</td>
                    <td class="field adress">Heuweidli<br>+41 44 938 38 40<br></td>
                    <td class="field city">8340 Hinwil</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">X-Sion Sports & Fashion</td>
                    <td class="field adress">Hauptstraße<br>+41 44 687 88 32<br></td>
                    <td class="field city">8832 Wollerau</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Balzer Sport</td>
                    <td class="field adress">Rüti<br>+41 81 382 21 41<br></td>
                    <td class="field city">7076 Parpan</td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>
    <!-- indexer::continue -->

    <strong>Südtirol</strong>
    <!-- indexer::stop -->
    <section class="mod_cataloglist block">
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Sport Mode Schönhuber</td>
                    <td class="field adress">Stadtgasse 24<br>+39 474 555141<br></td>
                    <td class="field city">39031 Bruneck-Brunico</td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>

    <strong>E-Commerce</strong>

    <!-- indexer::stop -->
    <section class="mod_cataloglist block">
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Bergfreunde.de</td>
                    <td class="field adress"><a href="http://www.bergfreunde.de/marken/pyua/" target="_blank">www.bergfreunde.de</a><br>+49 (0)7121 70 12 0<br></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Bergzeit.de</td>
                    <td class="field adress"><a href="http://www.bergzeit.de/pyua" target="_blank">www.bergzeit.de</a><br>+49 (0)8024 902290<br></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  odd">
                <tr class="item  odd">
                    <td class="field name">Blue Tomato</td>
                    <td class="field adress"><a href="http://www.blue-tomato.com/de-DE/brand/PYUA-6062/" target="_blank">www.blue-tomato.com</a><br>+49 (0)89 4161 4861<br></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  even">
                <tr class="item  even">
                    <td class="field name">EpicTV</td>
                    <td class="field adress"><a href="https://shop.epictv.com/en/products/?f[]=field_brand%3A2941" target="_blank">shop.epictv.com</a></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first odd">
                <tr class="item  first odd">
                    <td class="field name">Planet Sports</td>
                    <td class="field adress"><a href="https://www.planet-sports.de/marken/pyua/" target="_blank">www.planet-sports.de</a></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first even">
                <tr class="item  first even">
                    <td class="field name">Keller Sports</td>
                    <td class="field adress"><a href="http://www.keller-sports.de/marken/pyua/" target="_blank">www.keller-sports.de</a></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="layout_singleitem">
            <table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
                <tbody class="body  first odd">
                <tr class="item  first odd">
                    <td class="field name">Unterwegs - Der Outdoor Shop</td>
                    <td class="field adress"><a href="http://www.unterwegs.biz/" target="_blank">www.unterwegs.biz</a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>
    <!-- indexer::continue -->
</div>