<div class="category-products">
    <ul class="products-grid products-grid--max-3-col first last odd">
        <li class="nicetry item first" id="the-68-1" data-order="1">
            <a href="http://www.pyua.de/index.php/spark.html" title="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_spark_citrus-yellow_1z_21231002.jpg" alt="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark.html" title="Spark">Spark</a></h2>
                <div class="short-description">Isolationsschicht, Jacke für Damen</div>
                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                    <span class="price" id="old-price-68">229,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-68">149,95&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item" id="the-68-2" data-order="2">
            <a href="http://www.pyua.de/index.php/spark.html" title="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_spark_deep-lake-green_1z_21231002.jpg" alt="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark.html" title="Spark">Spark</a></h2>
                <div class="short-description">Isolationsschicht, Jacke für Damen</div>
                <span class="swatchLabel-category">Farbe:</span>
                <p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-68">229,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-68">149,95&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item last" id="the-68-3" data-order="3">
            <a href="http://www.pyua.de/index.php/spark.html" title="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_spark_navy-blue_1z_21231002.jpg" alt="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark.html" title="Spark">Spark</a></h2>
                <div class="short-description">
                    Isolationsschicht, Jacke für Damen                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">

                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                <span class="price" id="old-price-68">
                    229,95&nbsp;€                </span>
                    </p>

                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                <span class="price" id="product-price-68">
                    149,95&nbsp;€                </span>
                    </p>


                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-68-4" data-order="4">
            <a href="http://www.pyua.de/index.php/spark.html" title="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_spark_parrot-green_1z_21231002.jpg" alt="Isolationsschicht jacke fuer damen in deep lake green gruen modell spark von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark.html" title="Spark">Spark</a></h2>


                <div class="short-description">
                    Isolationsschicht, Jacke für Damen                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">

                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                <span class="price" id="old-price-68">
                    229,95&nbsp;€                </span>
                    </p>

                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                <span class="price" id="product-price-68">
                    149,95&nbsp;€                </span>
                    </p>


                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-29-1" data-order="1">
            <a href="http://www.pyua.de/index.php/spark-y.html" title="isolierende skijacke und snowboardjacke fuer herren in deep lake green gruen modell spark-y von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft-11231002_spark-y_deep-lake-green_1z.jpg" alt="isolierende skijacke und snowboardjacke fuer herren in deep lake green gruen modell spark-y von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark-y.html" title="Spark-Y">Spark-Y</a></h2>


                <div class="short-description">
                    Isolationsschicht, Jacke für Herren                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">

                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                <span class="price" id="old-price-29">
                    229,95&nbsp;€                </span>
                    </p>

                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                <span class="price" id="product-price-29">
                    149,95&nbsp;€                </span>
                    </p>


                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item" id="the-29-2" data-order="2">
            <a href="http://www.pyua.de/index.php/spark-y.html" title="isolierende skijacke und snowboardjacke fuer herren in deep lake green gruen modell spark-y von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft-11231002_spark-y_navy-blue_1z.jpg" alt="isolierende skijacke und snowboardjacke fuer herren in deep lake green gruen modell spark-y von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark-y.html" title="Spark-Y">Spark-Y</a></h2>


                <div class="short-description">
                    Isolationsschicht, Jacke für Herren                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">

                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                <span class="price" id="old-price-29">
                    229,95&nbsp;€                </span>
                    </p>

                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                <span class="price" id="product-price-29">
                    149,95&nbsp;€                </span>
                    </p>


                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item last" id="the-29-3" data-order="3">
            <a href="http://www.pyua.de/index.php/spark-y.html" title="isolierende skijacke und snowboardjacke fuer herren in deep lake green gruen modell spark-y von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft-11231002_spark-y_shocking-orange_1z.jpg" alt="isolierende skijacke und snowboardjacke fuer herren in deep lake green gruen modell spark-y von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/spark-y.html" title="Spark-Y">Spark-Y</a></h2>


                <div class="short-description">
                    Isolationsschicht, Jacke für Herren                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">

                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                <span class="price" id="old-price-29">
                    229,95&nbsp;€                </span>
                    </p>

                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                <span class="price" id="product-price-29">
                    149,95&nbsp;€                </span>
                    </p>


                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-69-1" data-order="1">
            <a href="http://www.pyua.de/index.php/glow.html" title="isolationsschicht, midlayer weste fuer damen in zitrus gelb modell glow von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_glow_citrus-yellow_1z_21232001.jpg" alt="isolationsschicht, midlayer weste fuer damen in zitrus gelb modell glow von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/glow.html" title="Glow">Glow</a></h2>


                <div class="short-description">
                    Isolationsschicht, Midlayer für Damen                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                                                                <span class="regular-price" id="product-price-69">
                                            <span class="price">89,95&nbsp;€</span>                                    </span>

                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item" id="the-69-2" data-order="2">
            <a href="http://www.pyua.de/index.php/glow.html" title="isolationsschicht, midlayer weste fuer damen in zitrus gelb modell glow von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_glow_navy-blue_1z_21232001.jpg" alt="isolationsschicht, midlayer weste fuer damen in zitrus gelb modell glow von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/glow.html" title="Glow">Glow</a></h2>


                <div class="short-description">
                    Isolationsschicht, Midlayer für Damen                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                                                                <span class="regular-price" id="product-price-69">
                                            <span class="price">89,95&nbsp;€</span>                                    </span>

                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-30-1" data-order="1">
            <a href="http://www.pyua.de/index.php/glow-y.html" title="isolationsschicht, midlayer weste fuer herren in deep lake green gruen modell glow-y von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_glow-y_deep-lake-green_1z_11232001_5.jpg" alt="isolationsschicht, midlayer weste fuer herren in deep lake green gruen modell glow-y von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/glow-y.html" title="Glow-Y">Glow-Y</a></h2>


                <div class="short-description">
                    Isolationsschicht, Midlayer für Herren                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                                                                <span class="regular-price" id="product-price-30">
                                            <span class="price">89,95&nbsp;€</span>                                    </span>

                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item" id="the-30-2" data-order="2">
            <a href="http://www.pyua.de/index.php/glow-y.html" title="isolationsschicht, midlayer weste fuer herren in deep lake green gruen modell glow-y von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_glow-y_navy-blue_1z_11232001_5.jpg" alt="isolationsschicht, midlayer weste fuer herren in deep lake green gruen modell glow-y von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/glow-y.html" title="Glow-Y">Glow-Y</a></h2>


                <div class="short-description">
                    Isolationsschicht, Midlayer für Herren                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                                                                <span class="regular-price" id="product-price-30">
                                            <span class="price">89,95&nbsp;€</span>                                    </span>

                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item last" id="the-30-3" data-order="3">
            <a href="http://www.pyua.de/index.php/glow-y.html" title="isolationsschicht, midlayer weste fuer herren in deep lake green gruen modell glow-y von pyua in frontansicht" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/p/r/primaloft_glow-y_shocking-orange_1z_11232001_5.jpg" alt="isolationsschicht, midlayer weste fuer herren in deep lake green gruen modell glow-y von pyua in frontansicht" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/glow-y.html" title="Glow-Y">Glow-Y</a></h2>


                <div class="short-description">
                    Isolationsschicht, Midlayer für Herren                                    </div>

                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                                                                <span class="regular-price" id="product-price-30">
                                            <span class="price">89,95&nbsp;€</span>                                    </span>

                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>