<div id="myshow1" class="protoshow for-stop">
	<ul class="cycle-slideshow" data-cycle-slides=".slide" data-cycle-fx=scrollHorz data-cycle-timeout=0 data-cycle-pause-on-hover=".for-stop" data-cycle-carousel-visible=1 data-cycle-next="#next" data-cycle-prev="#prev" data-cycle-pager="#pager" data-cycle-pager-template="<span></span>">
		<?php
		$staticBlockSlide01 = Mage::getModel('cms/block')->load('slide1');
		if($staticBlockSlide01->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide1')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide02 = Mage::getModel('cms/block')->load('slide2');
		if($staticBlockSlide02->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide2')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide03 = Mage::getModel('cms/block')->load('slide3');
		if($staticBlockSlide03->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide3')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide04 = Mage::getModel('cms/block')->load('slide4');
		if($staticBlockSlide04->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide4')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide05 = Mage::getModel('cms/block')->load('slide5');
		if($staticBlockSlide05->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide5')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide06 = Mage::getModel('cms/block')->load('slide6');
		if($staticBlockSlide06->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide6')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide07 = Mage::getModel('cms/block')->load('slide7');
		if($staticBlockSlide07->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide7')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide08 = Mage::getModel('cms/block')->load('slide8');
		if($staticBlockSlide08->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide8')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide09 = Mage::getModel('cms/block')->load('slide9');
		if($staticBlockSlide09->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide9')->toHTML();?></li>
		<?php } ?>

		<?php
		$staticBlockSlide10 = Mage::getModel('cms/block')->load('slide10');
		if($staticBlockSlide10->getIsActive() == 1) { ?>
		<li class="slide" data-slide-interval=""><?php echo  $this->getLayout()->createBlock('cms/block')->setBlockId('slide10')->toHTML();?></li>
		<?php } ?>
	</ul>
	<div class=center>
		<a href="#" id="prev"></a>
		<a href="#" id="next"></a>
	</div>

	<div class="cycle-pager" id="pager"></div>
</div>
