<h1>Hier ein kleiner Auszug der Produkte und des Utopia-Privileg Rabatts</h1>
<div class="category-products">
    <ul class="products-grid products-grid--max-3-col first last odd">
        <li class="nicetry item first" id="the-1331-1" data-order="1">
            <a href="http://www.pyua.de/index.php/backyard-y-yellow.html" title="Backyard-Y" class="product-image">
                <!-- Check if is out of Stock -->
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/s/k/skijacke-10411-402000_1.jpg" alt="Backyard-Y" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/backyard-y-yellow.html" title="Backyard-Y">Backyard-Y</a></h2>
                <div class="short-description">
                    Herren 3-Lagen-Jacke
                </div>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-1339">549,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-1339">412.46&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-1339-1" data-order="1">
            <a href="http://www.pyua.de/index.php/breakout-y.html" title="Breakout-Y" class="product-image">
                <!-- Check if is out of Stock -->
                <div class="neu-box"></div>
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/s/k/skitourenjacke-10413-508000_1.jpg" alt="Breakout-Y" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/breakout-y.html" title="Breakout-Y">Breakout-Y</a></h2>
                <div class="short-description">Herren 3-Lagen Jacke</div>
                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-1339">349,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-1339">262.46&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-1340-1" data-order="1">
            <a href="http://www.pyua.de/index.php/rush-y.html" title="Rush-Y" class="product-image">
                <!-- Check if is out of Stock -->
                <div class="neu-box"></div>
                <div class="neu-box"></div>
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/s/k/skipullover-herren-10429-211000_1.jpg" alt="Rush-Y" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/rush-y.html" title="Rush-Y">Rush-Y</a></h2>
                <div class="short-description">Herren Fleece-Pullover mit 1/2 Zip</div>
                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-1340">149,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-1340">112,46&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item" id="the-1338-2" data-order="2">
            <a href="http://www.pyua.de/index.php/fuse.html" title="leichte hybrid-isolationsjacke fuer damen in blau modell fuse von pyua in vorderansicht " class="product-image">
                <!-- Check if is out of Stock -->
                <div class="neu-box"></div>
                <div class="neu-box"></div>
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/i/s/isolationsjacke-damen-10428-211212_1.jpg" alt="leichte hybrid-isolationsjacke fuer damen in blau modell fuse von pyua in vorderansicht " height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/fuse.html" title="Fuse">Fuse</a></h2>
                <div class="short-description">Damen Isolationsjacke mit Kapuze</div>
                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-1338">299,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-1338">224.96&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item" id="the-1346-2" data-order="2">
            <a href="http://www.pyua.de/index.php/breakout.html" title="Breakout" class="product-image">
                <!-- Check if is out of Stock -->
                <div class="neu-box"></div>
                <div class="neu-box"></div>
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/1/0/10420_breakout_sulphur_yellow_1.jpg" alt="Breakout" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/breakout.html" title="Breakout">Breakout</a></h2>
                <div class="short-description">Damen 3-Lagen Jacke</div>
                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-1346">349,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-1346">262.46&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
        <li class="nicetry item first" id="the-1347-1" data-order="1">
            <a href="http://www.pyua.de/index.php/ascend.html" title="Ascend" class="product-image">
                <!-- Check if is out of Stock -->
                <div class="neu-box"></div>
                <div class="neu-box"></div>
                <img src="http://www.pyua.de/media/catalog/product/cache/1/base/275x275/9df78eab33525d08d6e5fb8d27136e95/s/p/sport-fleecejacke-damen-10432-211000_1.jpg" alt="Ascend" height="275" width="275"></a>
            <div class="product-info">
                <h2 class="product-name"><a href="http://www.pyua.de/index.php/ascend.html" title="Ascend">Ascend</a></h2>
                <div class="short-description">Damen Fleece-Jacke mit Kapuze</div>
                <span class="swatchLabel-category">Farbe:</span><p class="float-clearer"></p>
                <p class="float-clearer"></p>
                <div class="price-box">
                    <p class="old-price">
                        <span class="price-label">Regulärer Preis:</span>
                        <span class="price" id="old-price-1347">159,95&nbsp;€</span>
                    </p>
                    <p class="special-price">
                        <span class="price-label">Special Price</span>
                        <span class="price" id="product-price-1347">119.96&nbsp;€</span>
                    </p>
                </div>
                <span class="tax-details"><span class="tax-amount">Inkl. 19% MwSt.</span><br><span class="shipping-cost-details">zzgl. <a href="http://www.pyua.de/index.php/lieferung" class="shippinglink">Versandkosten</a></span></span>
                <p class="delivery-time">Lieferzeit: 2-3 Tage</p>
            </div>
        </li>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>