<h1>Händlerliste</h1>

<div style="margin-bottom:20px;" id="haendlersuche" class="mod_article block">

<strong>Deutschland</strong>
<!-- indexer::stop -->
<section class="mod_cataloglist block">

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
   <td class="field name">Love It Green</td>
   <td class="field adress">Eppendorfer Landstraße 98<br>+49 (0)40 65 86 69 55<br></td>
   <td class="field city">20249 Hamburg</td> 
   	
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Secret Spot Surfshop</td>
   <td class="field adress">Küterstraße 5<br>+49 (0)431 240 77 77<br></td>
   <td class="field city">24103 Kiel</td>
   
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  even">
  <tr class="item  even">
   <td class="field name">Extratour</td>
   <td class="field adress">Schauenburgerstraße 36<br>+49 (0)431 57 73 63<br></td>
   <td class="field city">24105 Kiel</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Angeln & Mehr</td>
   <td class="field adress">Langebrückstraße 20<br>+49 (0)431 76 72 76<br></td>
   <td class="field city">24340 Eckernförde</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  even">
  <tr class="item  even">
   <td class="field name">Native Souls</td>
   <td class="field adress">III. Hagen 29<br>+49 (0)152 5316 9732<br /></td>
   <td class="field city">45127 Essen</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Ski und Sport Profis</td>
   <td class="field adress">Töngesstraße 55<br>+49 (0)6136 95 33 88 1<br></td>
   <td class="field city">55129 Mainz</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  even">
  <tr class="item  even">
   <td class="field name">Breuninger</td>
   <td class="field adress">Am Main-Taunus-Zentrum<br>+49 (0)69 69 52 20 0<br></td>
   <td class="field city">65843 Sulzbach (Taunus)</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Breuninger</td>
   <td class="field adress">Marktstraße 1-3<br>+49 (0)711 21 10<br></td>
   <td class="field city">70173 Stuttgart</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  even">
  <tr class="item  even">
   <td class="field name">Sport Praxentaler</td>
   <td class="field adress">Maximilianstraße 2<br>+49 (0)861 98 78 24 9<br></td>
   <td class="field city">83278 Traunstein</td> 
   	
  </tr>
 </tbody>
</table>
</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Intersport Prosport</td>
   <td class="field adress">Grenzstraße 83<br>+49 (0)821 44 45 89 0<br></td>
   <td class="field city">86165 Augsburg</td> 
   	
  </tr>
 </tbody>
</table>
</div>


</section>
<!-- indexer::continue -->

<strong>Österreich</strong><!-- indexer::stop -->
<section class="mod_cataloglist block">

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first last even">
  <tr class="item  first last even">
   <td class="field name">Eco Lodge</td>
   <td class="field adress">Fohrafeld 11<br>+43 2748 74 06 0<br></td>
   <td class="field city">3233 Kilb</td> 
   	
  </tr>
 </tbody>
</table>
</div>


<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Sport Wöll</td>
   <td class="field adress">Pertisau 11c<br>+43 5243 58 71<br></td>
   <td class="field city">6213 Eben am Achensee</td> 
   	
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first last even">
  <tr class="item  first last even">
   <td class="field name">Sport Kessler</td>
   <td class="field adress">Walserstraße 73<br>+43 5517 36 85 40<br></td>
   <td class="field city">6991 Riezlern</td> 
   	
  </tr>
 </tbody>
</table>
</div>




</section>
<!-- indexer::continue -->

<strong>Schweiz</strong>
<!-- indexer::stop -->
<section class="mod_cataloglist block">

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
 <td class="field name">Sports Discount</td>
   <td class="field adress">Rue de Genève 17<br>+41 21 311 00 74<br></td>
   <td class="field city">1003 Lausanne</td> 
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Side Cut Sports</td>
   <td class="field adress">Gypsera 223<br>+41 26 412 10 58<br></td>
   <td class="field city">1716 Schwarzsee</td>
  </tr>
 </tbody>
</table>

</div>
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
 <td class="field name">Werrens Art</td>
   <td class="field adress">Rawilstrasse 10<br>+41 33 733 33 19<br></td>
   <td class="field city">3775 Lenk im Simmental</td> 
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Krüger Sport</td>
   <td class="field adress">Bahnhofstrasse 6<br>+41 27 927 14 63<br></td>
   <td class="field city">3987 Riederalp</td>
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
 <td class="field name">Number One</td>
   <td class="field adress">Pfistergasse 25<br>+41 41 241 01 21<br></td>
   <td class="field city">6003 Luzern</td> 
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">STS Sport Trend Shop</td>
   <td class="field adress">Heuweidli<br>+41 44 938 38 40<br></td>
   <td class="field city">8340 Hinwil</td>
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
 <td class="field name">X-Sion Sports & Fashion</td>
   <td class="field adress">Hauptstraße<br>+41 44 687 88 32<br></td>
   <td class="field city">8832 Wollerau</td> 
  </tr>
 </tbody>
</table>
</div>

</section>
<!-- indexer::continue -->


<strong>E-Commerce</strong>

<!-- indexer::stop -->
<section class="mod_cataloglist block">
<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Bergfreunde.de</td>
   <td class="field adress"><a href="http://www.bergfreunde.de/marken/pyua/" target="_blank">www.bergfreunde.de</a><br>+49 (0)7121 70 12 0<br></td>
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
 <td class="field name">Bergzeit.de</td>
   <td class="field adress"><a href="http://www.bergzeit.de/pyua" target="_blank">www.bergzeit.de</a><br>+49 (0)8024 902290<br></td>
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  odd">
  <tr class="item  odd">
   <td class="field name">Blue Tomato</td>
   <td class="field adress"><a href="http://www.blue-tomato.com/de-DE/brand/PYUA-6062/" target="_blank">www.blue-tomato.com</a><br>+49 (0)89 4161 4861<br></td>
  </tr>
 </tbody>
</table>
</div>

<div class="layout_singleitem">
<table cellspacing="0" cellpadding="0" summary="Catalog Items" class="layout_simpletable">
<tbody class="body  first even">
  <tr class="item  first even">
 <td class="field name">Frontlineshop</td>
   <td class="field adress"><a href="http://www.frontlineshop.com" target="_blank">www.frontlineshop.com</a><br>+49 (0)800 37 66 855<br></td>
  </tr>
 </tbody>
</table>
</div>
</section>
<!-- indexer::continue -->
</div>